In [1]:
#[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[30-08-2026]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]



import numpy as np 


## BASIC ARRAY CREATION 

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
# list 
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [4]:
a=[1,2,3.5,"Hello"]# If string value is removed it will convert it into Float 
a

[1, 2, 3.5, 'Hello']

In [6]:
np.array(a) # ALL data types got Converted To strings 

array(['1', '2', '3.5', 'Hello'], dtype='<U32')

In [10]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Generation Function 

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
# TO print matrix with 8 rows and 4 columns 
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np .ones ((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
arr=np.linspace(0,1,100) # creates space between same in all elements 
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Random Generation Function  

In [23]:
np.random.rand (10)# values comes in (0) with help of rand function

array([0.76496161, 0.53146509, 0.8629886 , 0.58152293, 0.36038679,
       0.92913208, 0.3287347 , 0.36064734, 0.70392224, 0.57829693])

In [24]:
np.random.randn(10)# values comes in (-) with help of randn function

array([-0.77322216,  0.1239687 , -1.30764346,  2.08272736, -0.01182397,
       -0.49823476, -0.00503609,  1.13834977, -0.8664287 , -2.24547801])

In [25]:
np.random.randint(9)# Generstes random number between 1 to 9 

7

In [26]:
np.random.randint(10,20,10)# Generstes random number between 10 to 20 but 10 numbers 

array([13, 16, 14, 16, 17, 14, 13, 11, 13, 11], dtype=int32)

## Array Attributes

In [39]:
arr=np.array ([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.shape # to check rows and columns 

(3, 3)

In [41]:
arr.size # to check elements in it 


9

In [42]:
arr.dtype #to check data types 

dtype('int64')

## Array Methods 

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.min() # Used To Check Miniumum Element in Array 

np.int64(1)

In [47]:
arr.max ()# Used To Check MAximum  Element in Array 

np.int64(9)

In [48]:
arr.sum() # To Do Sum 

np.int64(45)

In [49]:
np.sum(arr,axis = 0) # It creates Sum colums wise 

array([12, 15, 18])

In [50]:
np.sum(arr,axis = 1) # It creates Sum Row  wise 

array([ 6, 15, 24])

In [51]:
arr.mean() # Used to calculate Mean 

np.float64(5.0)

In [52]:
arr.std()

np.float64(2.581988897471611)

In [53]:
arr.argmin() #To know index 

np.int64(0)

## Reshaping And Resizing 

In [54]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr.reshape (6,5)# Total Elements Sould Fit in it means 30 == 5 x 3 =30

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])