In [5]:
import numpy as np 


## ARRAY OPERATIONS


### Arithematic operation

In [6]:
a1 =np.array([1,2,3,4,5])
a2 =np.array([6,7,8,9,10])


In [7]:
a1 + a2# Elements in Array Should be same


array([ 7,  9, 11, 13, 15])

In [8]:
a1-a2

array([-5, -5, -5, -5, -5])

In [9]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [12]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

## BROADCASTING 

In [13]:
l =[10,20,30,40]
arr=np.array(l)

In [14]:
for i in l:
 print (i+ 10) # Insted of this we can use 

20
30
40
50


In [15]:
arr+10

array([20, 30, 40, 50])

In [16]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr2+10 # WE Can Perform all Above  Operations On Matrix as Well  

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep and Shallow copy 

In [18]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a[4:6]*10

array([50, 60])

In [22]:
a
b=a

In [23]:
b[0]=99


In [24]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### MATRIX OPERATIONS

In [27]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [28]:
A

array([[1, 2],
       [3, 4]])

In [29]:
B

array([[5, 6],
       [7, 8]])

In [30]:
A @ B # For Multiplication of two matrix 

array([[19, 22],
       [43, 50]])

In [31]:
np.dot(A,B) # DOT MUltiplication 

array([[19, 22],
       [43, 50]])

In [32]:
# TO Take Transpose Of Matrix 
A.T

array([[1, 3],
       [2, 4]])

## ADVANCE ARRAY MANIPULATION 

#### Stacking Array 

In [33]:
A

array([[1, 2],
       [3, 4]])

In [34]:
B

array([[5, 6],
       [7, 8]])

In [36]:
# USED TO JOIN 2 ARRAY 
a= np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])


In [37]:
a

array([1, 2, 3, 4, 5])

In [38]:
b

array([ 6,  7,  8,  9, 10])

In [39]:
np.vstack((a,b)) # TO CReATe A VERTICAL STack 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
np.hstack((a,b)) # TO CReATe A HORIZONTAL STACK 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### SPLITTING ARRAY 

In [46]:
c=np.arange(16).reshape(4,4)

In [47]:
np.hsplit(c,2) # ARRAY IS SPLITE INTO TWO PARTS  there should be equal division 

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [48]:
np.vsplit(c,2) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]