In [54]:
import numpy as np 

## NUMPY INDEXING AND SLICING OF VECTORS 

In [55]:
arr = np.arange(11,21)
arr  


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
arr[1:4]# [:4 it will go upto 4 th index from 0]
# [:] 0 to last element 

array([12, 13, 14])

In [57]:
arr[1::2]# Skips into 2 steps 

array([12, 14, 16, 18, 20])

In [58]:
arr[4]

np.int64(15)

In [59]:
## NUMPY INDEXING AND SLICEING OF MATRIX 

In [60]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [61]:
arr[5]# 5th row is selected 

array([26, 27, 28, 29, 30])

In [62]:
# If we want to select 1 from above array we need to do 
arr[0,0]


np.int64(1)

In [63]:
arr[2,2] # FIRST ROW THEN COLUMN 


np.int64(13)

In [64]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [65]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [66]:
slice =arr [3:,3:]
slice


array([[19, 20],
       [24, 25],
       [29, 30]])

In [67]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## BOOLEAN INDEXING 

In [68]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [69]:
bool_index=arr%2 == 0 # It helps to give even numbers 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [70]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])